theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: Cucumber Utils
description: A Java library which helps you rapidly develop a test framework and write organized and clean Cucumber tests
author: Florin Slevoaca
url: https://fslev.github.io/cucumber-utils
permalink: pretty